# Generated by Django 4.2 on 2023-05-11 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('subType', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('deteailedName', models.CharField(max_length=1000)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('self', models.JSONField()),
                ('timeZoneOffset', models.TimeField()),
                ('iataCode', models.CharField(max_length=63)),
                ('geoCode', models.JSONField()),
                ('address', models.JSONField()),
                ('analytics', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
