# Generated by Django 4.2 on 2023-05-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='type_travel',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
